project:
  type: website
  resources:
    - "assets/*"
  post-render: order_posts.R

execute:
  freeze: auto  # Only re-execute code when source changes

website:
  title: "Econometrics and Free Software"
  site-url: https://b-rodrigues.github.io/
  favicon: assets/img/favicon-32x32.png

format:
  html:
    theme: solar
    css: styles.css
    mainfont: "IBM Plex Serif"
    monofont: "IBM Plex Mono"
    highlight-style: github
    toc: false
    include-in-header:
        text: |
            <style>
            @import url('https://fonts.bunny.net/css2?family=IBM+Plex+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=IBM+Plex+Serif:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap');
            </style>
            <table width="100%" height="100%" style="text-align: center;">
                <td>
                  <a href="https://b-rodrigues.github.io/blog/">Website</a> - 
                  <a href="https://www.youtube.com/@brodriguesco">Youtube</a> - 
                  <a href="https://b-rodrigues.github.io/blog/about.html">About</a> - 
                  <a href="https://b-rodrigues.github.io/blog/talks.html">Talks</a> -
                  <a href="https://b-rodrigues.github.io/blog/books.html">Books</a> - 
                  <a href="https://b-rodrigues.github.io/blog/packages.html">Packages</a> -
                  <a href="https://b-rodrigues.github.io/blog/index.xml">RSS</a>
                </td>
            </table>
    include-after-body: footer.html


